language: php 

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

notifications:
  email: false
  irc: "irc.efnet.org#php.zys"
   
env:
  - REPORT_EXIT_STATUS=1 NO_INTERACTION=1

#Compile
before_script:
    - ./travis/compile.sh

# Run PHPs run-tests.php 
script: make test